openapi: 3.0.0
info:
  title: Space2Study-UA API
  version: "1.0.0"
  description: "API docs for Space2Study UA"
servers:
  - url: http://localhost:8080
    description: Local dev
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
  /category:
    get:
      summary: Categories
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: Category name
                      required: true
                    appearance:
                      type: object
                      properties:
                        icon:
                          type: string
                          example: mocked-path-to-icon
                        color:
                          type: string
                          example: '#66C42C'
  /category/names:
    get:
      summary: Category names
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: Category name
  /category/{id}:
    get:
      summary: Category by id
      parameters:
        - name: id
          in: path
          required: true
          description: "ID of the category"
          allowEmptyValue: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: Category name
                    required: true
                  appearance:
                    type: object
                    properties:
                      icon:
                        type: string
                        example: mocked-path-to-icon
                      color:
                        type: string
                        example: '#66C42C'
