name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  Test_DEV:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout the Repo'
        uses: actions/checkout@v3

      # - name: Run DB

      - name: 'Install Node.js v.18'
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 'Start MongoDB'
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: latest
          mongodb-port: 27017
          mongodb-username: ${{secrets.MONGODB_USER}}
          mongodb-password: ${{secrets.MONGODB_PASS}}
          mongodb-db: 'space2study'

      - name: 'Wait for the database to start'
        run: |
          wget -qO- https://raw.githubusercontent.com/eficode/wait-for/refs/tags/$WAIT_FOR_VERSION/wait-for | 
          sh -s -- localhost:27017 -- echo "Database is up"
        env:
          WAIT_FOR_VERSION: v2.2.4

      - name: 'Install dependencies'
        run: npm install

      - name: 'Set .env.local'
        run: |
          echo "
          MONGODB_URL=mongodb://${{secrets.MONGODB_USER}}:${{secrets.MONGODB_PASS}}@localhost:27017/space2study?authSource=admin
          CLIENT_URL=http://localhost:3000
          SERVER_URL=http://localhost:8080
          SERVER_PORT=8080
          MAIL_USER=s2steam102@gmail.com
          MAIL_PASS=${{secrets.MAIL_PASS}}
          MAIL_FIRSTNAME=TestName
          MAIL_LASTNAME=TestSurname
          GMAIL_CLIENT_ID=${{secrets.GMAIL_CLIENT_ID}}.apps.googleusercontent.com
          GMAIL_CLIENT_SECRET=${{secrets.GMAIL_CLIENT_SECRET}}
          GMAIL_REFRESH_TOKEN=${{secrets.GMAIL_REFRESH_TOKEN}}
          GMAIL_REDIRECT_URI=https://developers.google.com/oauthplayground
          VITE_API_BASE_PATH=
          VITE_GMAIL_CLIENT_ID=
          COOKIE_DOMAIN=
          JWT_ACCESS_SECRET=${{secrets.JWT_ACCESS_SECRET}}
          JWT_REFRESH_SECRET=${{secrets.JWT_REFRESH_SECRET}}
          JWT_CONFIRM_SECRET=
          JWT_RESET_SECRET=
          JWT_ACCESS_EXPIRES_IN=1h
          JWT_REFRESH_EXPIRES_IN=24h
          JWT_RESET_EXPIRES_IN=24h
          JWT_CONFIRM_EXPIRES_IN=24h
          " > .env.local

      - name: 'Run Tests'
        run: npm run test:ci
        env:
          CI: true
          NODE_OPTIONS: --max_old_space_size=4096

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@master
        if: success() || failure()
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
